INFO flwr 2024-01-17 15:24:01,701 | app.py:148 | Starting Flower server, config: ServerConfig(num_rounds=400, round_timeout=None)
INFO flwr 2024-01-17 15:24:01,811 | app.py:168 | Flower ECE: gRPC server running (400 rounds), SSL is disabled
INFO flwr 2024-01-17 15:24:01,811 | server.py:86 | Initializing global parameters
INFO flwr 2024-01-17 15:24:01,811 | server.py:269 | Using initial parameters provided by strategy
INFO flwr 2024-01-17 15:24:01,811 | server.py:88 | Evaluating initial parameters
server booted up. starting clients...
INFO flwr 2024-01-17 15:24:02,821 | server.py:91 | initial parameters (loss, other metrics): 2.306342615768921, {'accuracy': 0.0913}
INFO flwr 2024-01-17 15:24:02,821 | server.py:101 | FL starting
INFO flwr 2024-01-17 15:25:11,420 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-17 15:25:11,421 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-17 15:25:11,421 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-17 15:25:11,425 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-17 15:25:11,434 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-17 15:25:11,436 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-17 15:25:11,436 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-17 15:25:11,437 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-17 15:25:11,452 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-17 15:25:11,453 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-17 15:25:11,453 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-17 15:25:11,457 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-17 15:25:11,474 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-17 15:25:11,476 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-17 15:25:11,476 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-17 15:25:11,480 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-17 15:25:11,482 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-17 15:25:11,483 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-17 15:25:11,483 | connection.py:39 | ChannelConnectivity.CONNECTING
INFO flwr 2024-01-17 15:25:11,484 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-17 15:25:11,485 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-17 15:25:11,485 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-17 15:25:11,486 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-17 15:25:11,487 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-17 15:25:11,488 | connection.py:39 | ChannelConnectivity.READY
DEBUG flwr 2024-01-17 15:25:11,488 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-17 15:25:11,489 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-17 15:25:11,492 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-17 15:25:11,510 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-17 15:25:11,511 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-17 15:25:11,511 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-17 15:25:11,514 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-17 15:25:11,775 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-17 15:25:11,776 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-17 15:25:11,776 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-17 15:25:11,780 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-17 15:25:11,781 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-17 15:25:11,782 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-17 15:25:11,782 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-17 15:25:11,786 | connection.py:39 | ChannelConnectivity.READY
DEBUG flwr 2024-01-17 15:29:41,461 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-17 15:29:41,518 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-17 15:29:41,664 | connection.py:113 | gRPC channel closed
booting up client 0
Traceback (most recent call last):
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/RP_FL/run_client.py", line 55, in <module>
    fl.client.start_numpy_client(server_address = "[::]:8080", client = client)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 252, in start_numpy_client
    start_client(
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 174, in start_client
    server_message = receive()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/grpc_client/connection.py", line 105, in <lambda>
    receive: Callable[[], ServerMessage] = lambda: next(server_message_iterator)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 541, in __next__
    return self._next()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 967, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "ping timeout"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2024-01-17T15:29:41.460653606+01:00", grpc_status:14, grpc_message:"ping timeout"}"
>
DEBUG flwr 2024-01-17 15:29:41,721 | connection.py:113 | gRPC channel closed
booting up client 0
Traceback (most recent call last):
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/RP_FL/run_client.py", line 55, in <module>
    fl.client.start_numpy_client(server_address = "[::]:8080", client = client)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 252, in start_numpy_client
    start_client(
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 174, in start_client
    server_message = receive()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/grpc_client/connection.py", line 105, in <lambda>
    receive: Callable[[], ServerMessage] = lambda: next(server_message_iterator)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 541, in __next__
    return self._next()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 967, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "ping timeout"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2024-01-17T15:29:41.5174238+01:00", grpc_status:14, grpc_message:"ping timeout"}"
>
srun: error: gpu05: tasks 4,8: Exited with exit code 1
srun: launch/slurm: _step_signal: Terminating StepId=9231384.1
slurmstepd: error: *** STEP 9231384.1 ON gpu05 CANCELLED AT 2024-01-17T15:29:42 ***
slurmstepd: error: common_file_write_content: unable to open '/sys/fs/cgroup/freezer/slurm/uid_618619/job_9231384/step_1/freezer.state' for writing: Permission denied
srun: error: gpu05: tasks 0-3,5-7,9: Terminated
srun: Force Terminated StepId=9231384.1
