INFO flwr 2024-01-17 15:23:56,167 | app.py:148 | Starting Flower server, config: ServerConfig(num_rounds=400, round_timeout=None)
server booted up. starting clients...
INFO flwr 2024-01-17 15:23:56,177 | app.py:168 | Flower ECE: gRPC server running (400 rounds), SSL is disabled
INFO flwr 2024-01-17 15:23:56,177 | server.py:86 | Initializing global parameters
INFO flwr 2024-01-17 15:23:56,177 | server.py:273 | Requesting initial parameters from one random client
INFO flwr 2024-01-17 15:24:56,128 | server.py:277 | Received initial parameters from one random client
INFO flwr 2024-01-17 15:24:56,129 | server.py:88 | Evaluating initial parameters
INFO flwr 2024-01-17 15:24:57,109 | server.py:91 | initial parameters (loss, other metrics): 2.306140386185428, {'accuracy': 0.1049}
INFO flwr 2024-01-17 15:24:57,110 | server.py:101 | FL starting
INFO flwr 2024-01-17 15:25:08,522 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-17 15:25:08,523 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-17 15:25:08,523 | connection.py:39 | ChannelConnectivity.CONNECTING
INFO flwr 2024-01-17 15:25:08,526 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
INFO flwr 2024-01-17 15:25:08,526 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-17 15:25:08,527 | connection.py:39 | ChannelConnectivity.READY
DEBUG flwr 2024-01-17 15:25:08,527 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-17 15:25:08,528 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-17 15:25:08,528 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-17 15:25:08,528 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-17 15:25:08,531 | connection.py:39 | ChannelConnectivity.READY
DEBUG flwr 2024-01-17 15:25:08,531 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-17 15:25:08,536 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-17 15:25:08,537 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-17 15:25:08,537 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-17 15:25:08,540 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-17 15:25:08,556 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-17 15:25:08,557 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-17 15:25:08,557 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-17 15:25:08,560 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-17 15:25:08,594 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-17 15:25:08,595 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-17 15:25:08,596 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-17 15:25:08,599 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-17 15:25:08,674 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-17 15:25:08,676 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-17 15:25:08,676 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-17 15:25:08,679 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-17 15:25:08,682 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-17 15:25:08,683 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-17 15:25:08,683 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-17 15:25:08,687 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-17 15:25:08,699 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-17 15:25:08,700 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-17 15:25:08,700 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-17 15:25:08,704 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-17 15:25:08,715 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-17 15:25:08,716 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-17 15:25:08,716 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-17 15:25:08,720 | connection.py:39 | ChannelConnectivity.READY
DEBUG flwr 2024-01-17 15:29:41,133 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-17 15:29:41,147 | connection.py:113 | gRPC channel closed
booting up client 0
Traceback (most recent call last):
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/RP_FL/run_client.py", line 55, in <module>
    fl.client.start_numpy_client(server_address = "[::]:8080", client = client)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 252, in start_numpy_client
    start_client(
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 174, in start_client
    server_message = receive()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/grpc_client/connection.py", line 105, in <lambda>
    receive: Callable[[], ServerMessage] = lambda: next(server_message_iterator)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 541, in __next__
    return self._next()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 967, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "ping timeout"
	debug_error_string = "UNKNOWN:Error received from peer ipv6:%5B::%5D:8080 {grpc_message:"ping timeout", grpc_status:14, created_time:"2024-01-17T15:29:41.146199327+01:00"}"
>
DEBUG flwr 2024-01-17 15:29:41,337 | connection.py:113 | gRPC channel closed
booting up client 0
Traceback (most recent call last):
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/RP_FL/run_client.py", line 55, in <module>
    fl.client.start_numpy_client(server_address = "[::]:8080", client = client)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 252, in start_numpy_client
    start_client(
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 174, in start_client
    server_message = receive()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/grpc_client/connection.py", line 105, in <lambda>
    receive: Callable[[], ServerMessage] = lambda: next(server_message_iterator)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 541, in __next__
    return self._next()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 967, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "ping timeout"
	debug_error_string = "UNKNOWN:Error received from peer ipv6:%5B::%5D:8080 {created_time:"2024-01-17T15:29:41.133235654+01:00", grpc_status:14, grpc_message:"ping timeout"}"
>
srun: error: gpu05: task 2: Exited with exit code 1
srun: launch/slurm: _step_signal: Terminating StepId=9231383.1
slurmstepd: error: *** STEP 9231383.1 ON gpu05 CANCELLED AT 2024-01-17T15:29:41 ***
slurmstepd: error: common_file_write_content: unable to open '/sys/fs/cgroup/freezer/slurm/uid_618619/job_9231383/step_1/freezer.state' for writing: Permission denied
srun: error: gpu05: tasks 0,3-9: Terminated
srun: error: gpu05: task 1: Exited with exit code 1
srun: Force Terminated StepId=9231383.1
