INFO flwr 2024-01-18 11:20:34,694 | app.py:148 | Starting Flower server, config: ServerConfig(num_rounds=400, round_timeout=None)
INFO flwr 2024-01-18 11:20:34,827 | app.py:168 | Flower ECE: gRPC server running (400 rounds), SSL is disabled
INFO flwr 2024-01-18 11:20:34,827 | server.py:86 | Initializing global parameters
INFO flwr 2024-01-18 11:20:34,828 | server.py:273 | Requesting initial parameters from one random client
server booted up. starting clients...
INFO flwr 2024-01-18 11:21:55,335 | server.py:277 | Received initial parameters from one random client
INFO flwr 2024-01-18 11:21:55,336 | server.py:88 | Evaluating initial parameters
INFO flwr 2024-01-18 11:21:57,301 | server.py:91 | initial parameters (loss, other metrics): 2.304904726889702, {'accuracy': 0.0789}
INFO flwr 2024-01-18 11:21:57,301 | server.py:101 | FL starting
INFO flwr 2024-01-18 11:22:02,860 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-18 11:22:02,865 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-18 11:22:02,865 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-18 11:22:02,869 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-18 11:22:03,020 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-18 11:22:03,022 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-18 11:22:03,022 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-18 11:22:03,027 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-18 11:22:03,064 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-18 11:22:03,066 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-18 11:22:03,066 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-18 11:22:03,070 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-18 11:22:03,135 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-18 11:22:03,138 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-18 11:22:03,138 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-18 11:22:03,142 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-18 11:22:03,222 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-18 11:22:03,225 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-18 11:22:03,226 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-18 11:22:03,230 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-18 11:22:03,431 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-18 11:22:03,434 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-18 11:22:03,434 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-18 11:22:03,438 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-18 11:22:03,632 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-18 11:22:03,638 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-18 11:22:03,638 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-18 11:22:03,642 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-18 11:22:03,696 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-18 11:22:03,698 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-18 11:22:03,701 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-18 11:22:03,702 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-18 11:22:03,950 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
INFO flwr 2024-01-18 11:22:03,971 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-18 11:22:03,974 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-18 11:22:03,974 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-18 11:22:03,979 | connection.py:39 | ChannelConnectivity.READY
DEBUG flwr 2024-01-18 11:22:04,010 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-18 11:22:04,010 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-18 11:22:04,014 | connection.py:39 | ChannelConnectivity.READY
DEBUG flwr 2024-01-18 11:23:58,604 | server.py:218 | fit_round 1: strategy sampled 10 clients (out of 10)
DEBUG flwr 2024-01-18 11:24:12,377 | server.py:232 | fit_round 1 received 10 results and 0 failures
WARNING flwr 2024-01-18 11:24:12,398 | fedavg.py:243 | No fit_metrics_aggregation_fn provided
INFO flwr 2024-01-18 11:24:14,442 | server.py:119 | fit progress: (1, 2.2905103297864193, {'accuracy': 0.1102}, 137.14104093471542)
INFO flwr 2024-01-18 11:24:14,443 | server.py:166 | evaluate_round 1: no clients selected, cancel
DEBUG flwr 2024-01-18 11:24:14,443 | server.py:218 | fit_round 2: strategy sampled 14 clients (out of 14)
DEBUG flwr 2024-01-18 11:24:24,684 | server.py:232 | fit_round 2 received 14 results and 0 failures
INFO flwr 2024-01-18 11:24:26,739 | server.py:119 | fit progress: (2, 2.273141451721649, {'accuracy': 0.1654}, 149.43742928281426)
INFO flwr 2024-01-18 11:24:26,739 | server.py:166 | evaluate_round 2: no clients selected, cancel
DEBUG flwr 2024-01-18 11:26:40,695 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-18 11:26:40,695 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-18 11:26:40,695 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-18 11:26:40,899 | connection.py:113 | gRPC channel closed
DEBUG flwr 2024-01-18 11:26:40,899 | connection.py:113 | gRPC channel closed
booting up client 6
Traceback (most recent call last):
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/RP_FL/run_client.py", line 55, in <module>
booting up client 2
DEBUG flwr 2024-01-18 11:26:40,899 | connection.py:113 | gRPC channel closed
Traceback (most recent call last):
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/RP_FL/run_client.py", line 55, in <module>
booting up client 8
Traceback (most recent call last):
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/RP_FL/run_client.py", line 55, in <module>
    fl.client.start_numpy_client(server_address = "[::]:8080", client = client)
    fl.client.start_numpy_client(server_address = "[::]:8080", client = client)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 252, in start_numpy_client
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 252, in start_numpy_client
    fl.client.start_numpy_client(server_address = "[::]:8080", client = client)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 252, in start_numpy_client
    start_client(
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 174, in start_client
    start_client(
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 174, in start_client
    start_client(
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 174, in start_client
    server_message = receive()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/grpc_client/connection.py", line 105, in <lambda>
    server_message = receive()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/grpc_client/connection.py", line 105, in <lambda>
    server_message = receive()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/grpc_client/connection.py", line 105, in <lambda>
    receive: Callable[[], ServerMessage] = lambda: next(server_message_iterator)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 541, in __next__
    receive: Callable[[], ServerMessage] = lambda: next(server_message_iterator)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 541, in __next__
    receive: Callable[[], ServerMessage] = lambda: next(server_message_iterator)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 541, in __next__
    return self._next()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 967, in _next
    return self._next()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 967, in _next
    return self._next()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 967, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "UNKNOWN:Error received from peer ipv6:%5B::%5D:8080 {created_time:"2024-01-18T11:26:40.693215694+01:00", grpc_status:14, grpc_message:"Socket closed"}"
>
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "UNKNOWN:Error received from peer ipv6:%5B::%5D:8080 {grpc_message:"Socket closed", grpc_status:14, created_time:"2024-01-18T11:26:40.693216155+01:00"}"
>
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "UNKNOWN:Error received from peer ipv6:%5B::%5D:8080 {grpc_message:"Socket closed", grpc_status:14, created_time:"2024-01-18T11:26:40.693352592+01:00"}"
>
DEBUG flwr 2024-01-18 11:26:41,723 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-18 11:26:41,723 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-18 11:26:41,724 | connection.py:39 | ChannelConnectivity.IDLE
srun: error: influ4: task 8: Exited with exit code 1
srun: launch/slurm: _step_signal: Terminating StepId=9232961.1
slurmstepd: error: *** STEP 9232961.1 ON influ4 CANCELLED AT 2024-01-18T11:26:41 ***
srun: error: influ4: tasks 0-7,9: Terminated
srun: Force Terminated StepId=9232961.1
