INFO flwr 2024-01-17 15:23:03,697 | app.py:148 | Starting Flower server, config: ServerConfig(num_rounds=400, round_timeout=None)
INFO flwr 2024-01-17 15:23:03,866 | app.py:168 | Flower ECE: gRPC server running (400 rounds), SSL is disabled
INFO flwr 2024-01-17 15:23:03,867 | server.py:86 | Initializing global parameters
INFO flwr 2024-01-17 15:23:03,867 | server.py:273 | Requesting initial parameters from one random client
server booted up. starting clients...
INFO flwr 2024-01-17 15:24:24,567 | server.py:277 | Received initial parameters from one random client
INFO flwr 2024-01-17 15:24:24,567 | server.py:88 | Evaluating initial parameters
INFO flwr 2024-01-17 15:24:25,621 | server.py:91 | initial parameters (loss, other metrics): 2.3073882896362785, {'accuracy': 0.0891}
INFO flwr 2024-01-17 15:24:25,621 | server.py:101 | FL starting
INFO flwr 2024-01-17 15:24:29,042 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-17 15:24:29,043 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-17 15:24:29,043 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-17 15:24:29,047 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-17 15:24:29,386 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-17 15:24:29,387 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-17 15:24:29,387 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-17 15:24:29,390 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-17 15:24:29,438 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-17 15:24:29,439 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-17 15:24:29,439 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-17 15:24:29,443 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-17 15:24:29,639 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-17 15:24:29,640 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-17 15:24:29,641 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-17 15:24:29,644 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-17 15:24:29,671 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-17 15:24:29,673 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-17 15:24:29,674 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-17 15:24:29,677 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-17 15:24:29,740 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-17 15:24:29,741 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-17 15:24:29,741 | connection.py:39 | ChannelConnectivity.CONNECTING
INFO flwr 2024-01-17 15:24:29,743 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-17 15:24:29,744 | connection.py:39 | ChannelConnectivity.READY
DEBUG flwr 2024-01-17 15:24:29,746 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-17 15:24:29,746 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-17 15:24:29,750 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-17 15:24:29,755 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
INFO flwr 2024-01-17 15:24:29,756 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-17 15:24:29,757 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-17 15:24:29,758 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-17 15:24:29,758 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-17 15:24:29,758 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-17 15:24:29,761 | connection.py:39 | ChannelConnectivity.READY
DEBUG flwr 2024-01-17 15:24:29,761 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-17 15:24:29,773 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-17 15:24:29,775 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-17 15:24:29,775 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-17 15:24:29,778 | connection.py:39 | ChannelConnectivity.READY
DEBUG flwr 2024-01-17 15:40:14,642 | connection.py:113 | gRPC channel closed
INFO flwr 2024-01-17 15:40:14,643 | app.py:185 | Disconnect and shut down
booting up client 0
booting up client 0
DEBUG flwr 2024-01-17 15:57:02,225 | connection.py:113 | gRPC channel closed
INFO flwr 2024-01-17 15:57:02,225 | app.py:185 | Disconnect and shut down
DEBUG flwr 2024-01-17 15:57:15,342 | connection.py:113 | gRPC channel closed
INFO flwr 2024-01-17 15:57:15,342 | app.py:185 | Disconnect and shut down
booting up client 0
DEBUG flwr 2024-01-17 15:57:15,342 | connection.py:113 | gRPC channel closed
INFO flwr 2024-01-17 15:57:15,342 | app.py:185 | Disconnect and shut down
booting up client 0
DEBUG flwr 2024-01-17 19:22:36,489 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-17 19:22:36,489 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-17 19:22:36,489 | connection.py:113 | gRPC channel closed
booting up client 0
Traceback (most recent call last):
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/RP_FL/run_client.py", line 55, in <module>
    fl.client.start_numpy_client(server_address = "[::]:8080", client = client)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 252, in start_numpy_client
    start_client(
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 174, in start_client
    server_message = receive()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/grpc_client/connection.py", line 105, in <lambda>
    receive: Callable[[], ServerMessage] = lambda: next(server_message_iterator)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 541, in __next__
    return self._next()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 967, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2024-01-17T19:22:36.487236298+01:00", grpc_status:14, grpc_message:"Socket closed"}"
>
DEBUG flwr 2024-01-17 19:22:36,512 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-17 19:22:36,513 | connection.py:113 | gRPC channel closed
booting up client 0
Traceback (most recent call last):
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/RP_FL/run_client.py", line 55, in <module>
    fl.client.start_numpy_client(server_address = "[::]:8080", client = client)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 252, in start_numpy_client
    start_client(
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 174, in start_client
    server_message = receive()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/grpc_client/connection.py", line 105, in <lambda>
    receive: Callable[[], ServerMessage] = lambda: next(server_message_iterator)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 541, in __next__
    return self._next()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 967, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "UNKNOWN:Error received from peer ipv6:%5B::%5D:8080 {grpc_message:"Socket closed", grpc_status:14, created_time:"2024-01-17T19:22:36.511192396+01:00"}"
>
DEBUG flwr 2024-01-17 19:22:36,692 | connection.py:113 | gRPC channel closed
booting up client 0
Traceback (most recent call last):
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/RP_FL/run_client.py", line 55, in <module>
DEBUG flwr 2024-01-17 19:22:36,692 | connection.py:113 | gRPC channel closed
booting up client 0
Traceback (most recent call last):
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/RP_FL/run_client.py", line 55, in <module>
    fl.client.start_numpy_client(server_address = "[::]:8080", client = client)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 252, in start_numpy_client
    fl.client.start_numpy_client(server_address = "[::]:8080", client = client)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 252, in start_numpy_client
    start_client(
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 174, in start_client
    start_client(
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 174, in start_client
    server_message = receive()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/grpc_client/connection.py", line 105, in <lambda>
    server_message = receive()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/grpc_client/connection.py", line 105, in <lambda>
    receive: Callable[[], ServerMessage] = lambda: next(server_message_iterator)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 541, in __next__
    receive: Callable[[], ServerMessage] = lambda: next(server_message_iterator)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 541, in __next__
    return self._next()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 967, in _next
    return self._next()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 967, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2024-01-17T19:22:36.487354169+01:00", grpc_status:14, grpc_message:"Socket closed"}"
>
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Socket closed", grpc_status:14, created_time:"2024-01-17T19:22:36.487260934+01:00"}"
>
DEBUG flwr 2024-01-17 19:22:36,716 | connection.py:113 | gRPC channel closed
booting up client 0
Traceback (most recent call last):
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/RP_FL/run_client.py", line 55, in <module>
    fl.client.start_numpy_client(server_address = "[::]:8080", client = client)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 252, in start_numpy_client
    start_client(
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/app.py", line 174, in start_client
    server_message = receive()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/client/grpc_client/connection.py", line 105, in <lambda>
    receive: Callable[[], ServerMessage] = lambda: next(server_message_iterator)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 541, in __next__
    return self._next()
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/grpc/_channel.py", line 967, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "UNKNOWN:Error received from peer ipv6:%5B::%5D:8080 {grpc_message:"Socket closed", grpc_status:14, created_time:"2024-01-17T19:22:36.511185954+01:00"}"
>
srun: error: gpu03: tasks 2,5-6: Exited with exit code 1
srun: launch/slurm: _step_signal: Terminating StepId=9231375.1
slurmstepd: error: *** STEP 9231375.1 ON gpu03 CANCELLED AT 2024-01-17T19:22:36 ***
slurmstepd: error: common_file_write_content: unable to open '/sys/fs/cgroup/freezer/slurm/uid_618619/job_9231375/step_1/freezer.state' for writing: Permission denied
srun: error: gpu03: tasks 0,7-8: Terminated
srun: Force Terminated StepId=9231375.1
