INFO flwr 2024-01-17 15:23:03,690 | app.py:148 | Starting Flower server, config: ServerConfig(num_rounds=400, round_timeout=None)
INFO flwr 2024-01-17 15:23:03,866 | app.py:168 | Flower ECE: gRPC server running (400 rounds), SSL is disabled
INFO flwr 2024-01-17 15:23:03,867 | server.py:86 | Initializing global parameters
INFO flwr 2024-01-17 15:23:03,867 | server.py:273 | Requesting initial parameters from one random client
server booted up. starting clients...
INFO flwr 2024-01-17 15:24:25,557 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-17 15:24:25,559 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-17 15:24:25,559 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-17 15:24:25,562 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-17 15:24:26,209 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-17 15:24:26,210 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-17 15:24:26,210 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-17 15:24:26,214 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-17 15:24:26,219 | server.py:277 | Received initial parameters from one random client
INFO flwr 2024-01-17 15:24:26,221 | server.py:88 | Evaluating initial parameters
INFO flwr 2024-01-17 15:24:26,230 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-17 15:24:26,231 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-17 15:24:26,231 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-17 15:24:26,234 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-17 15:24:26,267 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-17 15:24:26,268 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-17 15:24:26,269 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-17 15:24:26,272 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-17 15:24:26,309 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-17 15:24:26,310 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-17 15:24:26,311 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-17 15:24:26,314 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-17 15:24:26,324 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-17 15:24:26,326 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-17 15:24:26,326 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-17 15:24:26,329 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-17 15:24:26,487 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-17 15:24:26,489 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-17 15:24:26,489 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-17 15:24:26,492 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-17 15:24:26,541 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-17 15:24:26,543 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-17 15:24:26,543 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-17 15:24:26,546 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-17 15:24:26,575 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-17 15:24:26,576 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-17 15:24:26,576 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-17 15:24:26,579 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-17 15:24:26,594 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-01-17 15:24:26,595 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2024-01-17 15:24:26,595 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2024-01-17 15:24:26,599 | connection.py:39 | ChannelConnectivity.READY
INFO flwr 2024-01-17 15:24:27,223 | server.py:91 | initial parameters (loss, other metrics): 2.304388192496207, {'accuracy': 0.1219}
INFO flwr 2024-01-17 15:24:27,223 | server.py:101 | FL starting
DEBUG flwr 2024-01-17 15:24:29,779 | server.py:218 | fit_round 1: strategy sampled 10 clients (out of 10)
DEBUG flwr 2024-01-17 15:24:34,859 | server.py:232 | fit_round 1 received 10 results and 0 failures
args.central: False
server strategy: ADMM
number of clients: 10
round:      0
Server-side evaluation loss 2.304388192496207 / accuracy 0.1219
Traceback (most recent call last):
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/RP_FL/run_server.py", line 161, in <module>
    fl.server.start_server(config=fl.server.ServerConfig(num_rounds=NUM_ROUNDS), strategy=strat)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/server/app.py", line 176, in start_server
    hist = _fl(
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/server/app.py", line 217, in _fl
    hist = server.fit(num_rounds=config.num_rounds, timeout=config.round_timeout)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/server/server.py", line 106, in fit
    res_fit = self.fit_round(server_round=current_round, timeout=timeout)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/envs/flower2en/lib/python3.9/site-packages/flwr/server/server.py", line 244, in fit_round
    ] = self.strategy.aggregate_fit(server_round, results, failures)
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/RP_FL/src/ADMM_strategy.py", line 28, in aggregate_fit
    y_local = json.loads(res.metrics["Y"].decode("utf-8"))
KeyError: 'Y'
DEBUG flwr 2024-01-17 15:57:02,225 | connection.py:113 | gRPC channel closed
INFO flwr 2024-01-17 15:57:02,225 | app.py:185 | Disconnect and shut down
booting up client 0
DEBUG flwr 2024-01-17 15:57:15,342 | connection.py:113 | gRPC channel closed
INFO flwr 2024-01-17 15:57:15,343 | app.py:185 | Disconnect and shut down
booting up client 0
DEBUG flwr 2024-01-17 16:13:19,192 | connection.py:113 | gRPC channel closed
INFO flwr 2024-01-17 16:13:19,193 | app.py:185 | Disconnect and shut down
DEBUG flwr 2024-01-17 16:13:19,193 | connection.py:113 | gRPC channel closed
INFO flwr 2024-01-17 16:13:19,193 | app.py:185 | Disconnect and shut down
booting up client 0
booting up client 0
DEBUG flwr 2024-01-17 16:13:19,193 | connection.py:113 | gRPC channel closed
INFO flwr 2024-01-17 16:13:19,193 | app.py:185 | Disconnect and shut down
booting up client 0
DEBUG flwr 2024-01-17 16:13:19,193 | connection.py:113 | gRPC channel closed
INFO flwr 2024-01-17 16:13:19,193 | app.py:185 | Disconnect and shut down
booting up client 0
DEBUG flwr 2024-01-17 16:13:19,193 | connection.py:113 | gRPC channel closed
INFO flwr 2024-01-17 16:13:19,193 | app.py:185 | Disconnect and shut down
booting up client 0
DEBUG flwr 2024-01-17 16:13:19,193 | connection.py:113 | gRPC channel closed
INFO flwr 2024-01-17 16:13:19,193 | app.py:185 | Disconnect and shut down
booting up client 0
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
slurmstepd: error: *** STEP 9231372.0 ON gpu03 CANCELLED AT 2024-01-17T19:22:36 DUE TO TIME LIMIT ***
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
DEBUG flwr 2024-01-17 19:22:36,490 | connection.py:113 | gRPC channel closed
booting up client 0
Traceback (most recent call last):
  File "/tudelft.net/staff-bulk/ewi/insy/DBL/swiergarst/RP_FL/run_client.py", line 55, in <module>
slurmstepd: error: *** JOB 9231372 ON gpu03 CANCELLED AT 2024-01-17T19:22:36 DUE TO TIME LIMIT ***
slurmstepd: error: *** STEP 9231372.1 ON gpu03 CANCELLED AT 2024-01-17T19:22:36 DUE TO TIME LIMIT ***
